version: '3.9'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3000:3000"
    volumes:
      - .:/front
      - front_node_modules:/front/node_modules
volumes:
  front_node_modules: